### ISSUE TITLE
Vagrant up fails at provisionning (merge_yaml)

### ISSUE THREAD

**Issue by IngridWeck** [puphpet/puphpet#1490]
https://gist.github.com/IngridWeck/bfca4b40bc4e7a52cfd1

tested on vagrant 1.7.2 and 1.7.1 on OS X 10.9.5 

any custom solution to replace merge_yaml would be acceptable.

Thanks to anyone taking some time to help me.
Regards

**Comment by jtreminio** [comment]
Weird!

`merge_yaml()` is in the puphpet-puppet module:

https://github.com/puphpet/puppet-puphpet/blob/master/lib/puppet/parser/functions/merge_yaml.rb

Can you `$ ls puphpet/puppet/modules` for me?

**Comment by IngridWeck** [comment]
indeed! 

https://gist.github.com/IngridWeck/3365c72f57550ac626bc

**Comment by Nakira** [comment]
@jtreminio @IngridWeck my bad i forgot to commit some puphpet files. U can close this issue

**Comment by php-daddy** [comment]
I've got the same issue.

```
==> default: Warning: Could not retrieve fact fqdn
==> default: Error: Could not autoload puppet/parser/functions/merge_yaml: cannot load such file -- active_support
==> default: Error: Could not autoload puppet/parser/functions/merge_yaml: cannot load such file -- active_support on node localhost
==> default: Error: Could not autoload puppet/parser/functions/merge_yaml: cannot load such file -- active_support on node localhost
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
➜  centos git:(master) ls puphpet/puppet/modules
apache        composer      epel          git           mailcatcher   mysql         percona       puphpet       rabbitmq      solr          stdlib        sysctl
apt           concat        erlang        java          mongodb       nginx         php           puppi         redis         sqlite        supervisord   vcsrepo
beanstalkd    elasticsearch firewall      locales       monitor       ntp           postgresql    pyenv         rvm           staging       swap_file     yum
```

**Comment by IngridWeck** [comment]
done

**Comment by paolooo** [comment]
@IngridWeck, What do you done? How did you fixed it?

**Comment by teslitsky** [comment]
Got the same issue. For me works only if specify an empty hostname in config.yaml instead of something like 'project.dev'.

**Comment by monkviper** [comment]
I am still having this issue. What should I do to fix it? 

anyone? please

**Comment by paolooo** [comment]
Yeah! I still got the same error with my old vagrant config. I've downloaded the new puphpet config and it fixed the issue. https://puphpet.com

**Comment by monkviper** [comment]
@paolooo but the same config works for other devs of my team.

**Comment by monkviper** [comment]
@php-daddy: did you fix the same issue?

**Comment by otravers** [comment]
I ran into the same issue and like @teslitsky solved with an empty hostname.

**Comment by leokun** [comment]
I had the same issue but with other errors above. it happend if you used a *.dev or *.local domain because they will be used soon.

My solution is to let the loca.puphpet, finish the initial `vagrant up` and the change the domain name

**Comment by gusdecool** [comment]
today generated puphpet, still got same error.

```
==> default: Error: Could not autoload puppet/parser/functions/merge_yaml: cannot load such file -- active_support
==> default: Error: Could not autoload puppet/parser/functions/merge_yaml: cannot load such file -- active_support on node local.puphpet
==> default: Error: Could not autoload puppet/parser/functions/merge_yaml: cannot load such file -- active_support on node local.puphpet
```

tried like @teslitsky & @leokun  suggest also not work,

**Comment by rncrtr** [comment]
I have this issue, which seems to be related to my being behind a corporate proxy.

**Comment by Nakira** [comment]
this error was due to missing puphpet files. Downloading fresh copy of puphet resolved the issue

**Comment by cadr-sa** [comment]
I've fixed the problem by changing the domain name from your-domain.dev to your-domain.local in config.yaml

hope this will solve your problem

**Comment by dinhkk** [comment]
Many thanks cadr-sa, you solved this. :)

**Comment by luispabon** [comment]
This is still an issue on vagrant boxes generated from the website. Tried generating it three times already. You can just load the site and go directly to generate the archive without configuring anything, try vagrant up.

Only way I could go forward is to actually manually install within the box "gem install activesupport", then fails at a different provisioning script. I just don't think any of the required gems are installing at all during first set up.

**Comment by nick-catanchin-ie** [comment]
@luispabon - seems to be a problem with `rubygems.org`

````bash
==> default: ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
==> default:     Errno::ENETUNREACH: Network is unreachable - connect(2) (https://api.rubygems.org/quick/Marshal.4.8/deep_merge-1.0.1.gemspec.rz)
==> default: ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
==> default:     Errno::ENETUNREACH: Network is unreachable - connect(2) (https://api.rubygems.org/quick/Marshal.4.8/activesupport-4.2.3.gemspec.rz)
==> default: ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
==> default:     Errno::ENETUNREACH: Network is unreachable - connect(2) (https://api.rubygems.org/quick/Marshal.4.8/vine-0.2.gemspec.rz)
````

**Comment by evancauwenberg** [comment]
I have the same issues:
```==> default: Error: Could not autoload puppet/parser/functions/merge_yaml: cannot load such file -- active_support
==> default: Error: Could not autoload puppet/parser/functions/merge_yaml: cannot load such file -- active_support on node boschbcs.dev
==> default: Error: Could not autoload puppet/parser/functions/merge_yaml: cannot load such file -- active_support on node boschbcs.dev

**Comment by luispabon** [comment]
I did revert to a different puphet machine for a different project which worked great. Also, quoting myself:

```
Only way I could go forward is to actually manually install within the box "gem install activesupport", then fails at a different provisioning script. I just don't think any of the required gems are installing at all during first set up.
```

There seemed to be an issue installing gems that weren't related to unreachable hosts. Manual gem install from cli worked fine.

**Comment by fousheezy** [comment]
I too encountered this issue when generating a new project today. I ran `gem install activesupport` and was able to proceed.

**Comment by MrNomNom** [comment]
This is not resolved. Was able to fix this changing hostname to xxxx.local.

**Comment by philbates35** [comment]
I just came across this issue generating a fresh box from the websites, so wanted to let you all know its still an issue. Like others, changing the host name from <appname>.dev to <appname>.local resolved the issue though.

**Comment by kaiyulee** [comment]
Oh NO， tried all above, issue still comes about.

**Comment by kaiyulee** [comment]
mybe，it's because of GFW,I cant download some file with GEM...

```
==> default: stdin: is not a tty
==> default: ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
==> default:     SSL_connect SYSCALL returned=5 errno=0 state=unknown state (https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/deep_merge-1.0.1.gemspec.rz)
==> default: ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
==> default:     SSL_connect SYSCALL returned=5 errno=0 state=unknown state (https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/activesupport-4.2.5.gemspec.rz)
==> default: ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
==> default:     SSL_connect SYSCALL returned=5 errno=0 state=unknown state (https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/vine-0.2.gemspec.rz)
```

I switch to google vpn, the *installation* goes farther more.
