### ISSUE TITLE
All boxes: vagran up fails due to ssh timeout

### ISSUE THREAD

**Issue by bke-daniel** [puphpet/puphpet#2475]
Hey there,

I'm not sure if it's a general issue, but what I've found out so far is:
- Appears on all existing boxes, except one:
  - CentOS 6 & 7 x64
  - Ubuntu Trusty 14.04 x64
  - Ubuntu Xenial 16.04 x64
  - Ubuntu Xenial 16.04 i386 not tested
- VB Logs don't help at all / not showing errors.

Versions I have:
- vagrant 1.8.6
- VirtualBox 5.0.26 r108824
- OSX Sierra 10.12
- Tried almost all combinations of PHP 5.6, 7 and MySQL 5.6 and 5.7
- nginx

What I've tried so far:
- On an existing box
  - used outdated boxes
  - provision -> fails
  - removed all and used latest boxes
  - provision -> fails
  - vagrant destroy; vagrant up -> fails
- On new boxes
  - used outdated boxes
  - vagrant up --> fails
  - removed all and used latest boxes
  - vagrant up --> fails
- Enabled GUI to see errors
- Used boxes with almost no configuration

On all boxes I got this terminal error:

```
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

Only in Ubuntu Xenial 16.04 x64 I got the following GUI message:

```
SMBus base address uninitialized - upgrade BIOS or use force_addr=0xaddr
```

Found [this](http://askubuntu.com/questions/298290/smbus-bios-error-while-booting-ubuntu-in-virtualbox), but didn't help at all because puphpet didn't do stuff.

It seems that when booting Trusty there's a messing going on but it's proceeding to the login screen. Sadly it's way to fast to screenshot or read it.

Any suggestions?

```
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/centos7-x64
                box_url: puphpet/centos7-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 1
                    vmware:
                        numvcpus: 1
                    parallels:
                        linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_9oz2mwx2j3lh:
                        id: he-we-xxxx-hevm-v1
                        hostname: he-we-xxxx-hevm-v1
                        network:
                            private_network: 192.168.56.165
                            forwarded_port:
                                vflmnfp_w2jzbjcm0byj:
                                    host: '7564'
                                    guest: '22'
                        memory: '4096'
                        cpus: '1'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path:
                    - puphpet/puppet/modules
                    - puphpet/puppet/manifests
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_upjmwq349ma1:
                source: ../he-we-xxxx-wp-theme/dist
                target: /var/www/wordpress/wp-content/themes/xxxx_v1
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
            vflsf_lnpahmxdsusk:
                source: ../he-we-xxxx-plugin/dist
                target: /var/www/wordpress/wp-content/plugins/helionmedia_xxxx
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages:
        - vim-common
        - wget
        - unzip
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: UTC
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '1'
    settings:
        version: present
        default_vhost: 1
        proxy_buffers: '4 256k'
        proxy_buffer_size: 128k
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_viv6mgo2xi58:
            server_name: xxxxx.dev
            server_aliases:
                - www.xxxx.dev
            www_root: /var/www/wordpress
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 3m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_j2xfktfjillu:
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_ybfs4qe85373:
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '0'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_1hwdeba4nqav:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_rivxcwsj603n:
                    path: /var/www/awesome
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_3l7icea1c406:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
letsencrypt:
    install: '1'
    settings:
        email: ''
    domains: {  }
php:
    install: '1'
    settings:
        version: '5.6'
    modules:
        php:
            - cli
            - intl
            - xml
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_00gokqufjfzj:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '0'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.24.1
drush:
    install: '0'
    version: 8.0.5
ruby:
    install: '1'
    versions:
        rv_6rsh3wqdjcgo:
            default: '1'
            bundler: '1'
            version: 2.3.1
            gems:
                - deep_merge@1.0.1
                - activesupport@4.2.6
                - vine@0.2
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    settings:
        version: '6'
    npm_packages: {  }
hhvm:
    install: '0'
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_xhwm0wbkhbv4:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_60ps9mbe2rhj:
            name: dbname
            sql: ''
    grants:
        mariadbng_mc1g0p5pdhoo:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: 123
        override_options: {  }
    adminer: '1'
    users: {  }
    databases:
        mysqlnd_zzol2ryryuv6:
            name: wordpress
            sql: ''
    grants: {  }
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.6'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '0'
    settings:
        port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.3.1
        java_install: true
    instances:
        esi_fmgxw428oixs:
            name: es-01
solr:
    install: '0'
    settings:
        version: 5.5.2
        port: '8984'

```

XXXX'd out a few things and also replaced passwords, maybe the nfs mount won't work on "vagrant up" but they do on my system with the real paths.

Also tried disabling "hwvirtex", but we're on x64 so I guess we can't disable it. At least VB activates it by itself. That's over my head maybe some can correct me, please.

Cheers,
Daniel

**Comment by obayesshelton** [comment]
I'm also getting this issue

**Comment by obayesshelton** [comment]
@bke-daniel I fixed it by updating to vagrant 1.8.6 and vBox 5.1.6 and it should work

**Comment by bke-daniel** [comment]
@obayesshelton You're absolutely right, sir! Thank you very much.
It's ridiculous, because I have been checking for updates within the VB app and it told me that there were no updates. So I wasn't heading for the website.
Long answer short. For me it's fixed.

**Comment by obayesshelton** [comment]
@bke-daniel I had the same issue, I went to vagrant and VirtualBox and downloaded both from scratch.

**Comment by bke-daniel** [comment]
UPDATE:
After playing around it seems that it's not fixed on all boxes. Still the error occurs on:
- Trusty
- Ubuntu Xenial 16.04 i386 not tested - maybe some has the time and / or machine

**Comment by obayesshelton** [comment]
👍

**Comment by coolfarmer** [comment]
I think I have the same problem. I just remove my old box like the homepage say and when I launch my VM I receive an SSH error. To be sure, I updated Vagrant to 1.8.6 (don't touch the version of VMware) and I receive again the same error.

So I downloaded **a fresh new box** generated via PhPHPet (with Ubuntu **Trusty**) and got the same error.

![2016-10-18_19-23-37](https://cloud.githubusercontent.com/assets/4965519/19500161/b674d4a6-9568-11e6-9ed7-706975627937.png)

**Comment by mobyjames** [comment]
Same issue.

- OS X Sierra
- Complete uninstall / reinstall of VirtualBox and Vagrant to latest versions
- Cannot boot any Ubuntu setup (freshly downloaded)

**Comment by Fynkymynky** [comment]
Similar problem

Vagrant 1.8.6
VirtualBox 5.1.8
OS X Sierra

Installing puphpet/ubuntu1604-x64 I get a timeout on SSH auth method: private key

**Comment by Fynkymynky** [comment]
Running puphpet/ubuntu1404-x64 it fails at the end of the provision stage

```
==> testfail: Error: Could not find a suitable provider for mysql_datadir
==> testfail: Error: Could not find a suitable provider for rvm_system_ruby
==> testfail: Error: Could not find a suitable provider for mysql_user
==> testfail: Error: Could not find a suitable provider for rvm_gem
==> testfail: Error: Could not find a suitable provider for mysql_database
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

HELP! I have work to do :'(

**Comment by rulin132** [comment]
Had the same issue

```
==> local: Waiting for machine to boot. This may take a few minutes...
    local: SSH address: 127.0.0.1:2222
    local: SSH username: vagrant
    local: SSH auth method: private key
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'paused' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

The primary issue for this error is that the provider you're using
is not properly configured. This is very rarely a Vagrant issue.
```

Further investigations reveal that the machine booted up fine, logged directly into the machine through Virtualbox and noticed i wasnt able to ping puphpet.com or google.com.

Looking into the network configuration, I found that "Cable Connected" was disabled, I re-enabled and looks like it solved the problem.

![image](https://cloud.githubusercontent.com/assets/760159/19516353/524c43bc-9647-11e6-8ec8-9500c15ad83b.png)

**Comment by mrsimonbennett** [comment]
good stop @rulin132! Thanks

**Comment by coolfarmer** [comment]
@rulin132 , if you change the VM's config directly in Virtualbox you will have to do that every time you boot her. It's a good workaround (for virtualbox, I don't think I have this option on VMware), but I hope the dev will come with a fix.

It's not normal that a fresh VM on a fresh install of a provider + vagrant give us that error.

**Comment by rulin132** [comment]
@coolfarmer When I did a vagrant provision, halt and up, it seem to keep this option checked and allow me to ssh correctly into the server... I'm guessing this is happening on the initial setup of the box

**Comment by coolfarmer** [comment]
@jtreminio , what's your thought about this?

**Comment by StormTide** [comment]
Think this is the cableconnected1 bug. Use VirtualBox 5.1 or add 

cableconnected1: 'on' 

below natdnshostresolver1 in modifyvm block to use VirtualBox 5.0.x

You can also press escape at the ubuntu screen to see the network waiting message, and you can check the cable connected box in settings/network/advanced in virtualbox when vagrant is waiting to connect and it will work.

**Comment by tecnom1k3** [comment]
Checking the cable connected certainly did the trick for me too.

**Comment by coolfarmer** [comment]
@StormTide , unfortunately this doesn't work on VMware Workstation (in software or after adding the line in the config). This is very weird, I doesn't change anything, one day it work, one day it stop, grrrr. Vagrant and Puphpet are so unstable.

**Comment by ocaida** [comment]
Connect cable method also worked for me. Thank you @rulin132!

**Comment by StudioMaX** [comment]
For those who have similar issues and upgraded to VirtualBox 5.1.8 - try to downgrade to VirtualBox 5.1.6.
Right now the latest version of VirtualBox is totally unusable for me, there are a lot of errors like
```
...
==> sws: Info: Loading facts
==> sws: Info: Loading facts
==> sws: Info: Loading facts
==> sws: Error: Facter: error while resolving custom fact "nodejs_latest_version": end of file reached
==> sws: Error: Facter: error while resolving custom fact "nodejs_stable_version": end of file reached
```

```
==> sws: Notice: /Stage[main]/Puphpet::Mariadb::Repo::Debian/Apt::Key[199369E5404BD5FC7D2FE43BCBCB082A1BB943DB]/Anchor[apt_key 199369E5404BD5FC7D2FE43BCBCB082A1BB943DB present]: Dependency Apt_key[199369E5404BD5FC7D2FE43BCBCB082A1BB943DB] has failures: true
==> sws: Error: Execution of '/usr/bin/apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 199369E5404BD5FC7D2FE43BCBCB082A1BB943DB' returned 2: Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.zsbfA8IECV --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/ondrej-apache2.gpg --keyring /etc/apt/trusted.gpg.d/pdoes-ppa.gpg --keyring /etc/apt/trusted.gpg.d/puppetlabs-pc1-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 199369E5404BD5FC7D2FE43BCBCB082A1BB943DB
==> sws: gpg: requesting key 1BB943DB from hkp server keyserver.ubuntu.com
==> sws: ?: [fd 4]: read error: Connection reset by peer
==> sws: gpgkeys: key 199369E5404BD5FC7D2FE43BCBCB082A1BB943DB partially retrieved (probably corrupt)
==> sws: gpg: no valid OpenPGP data found.
==> sws: gpg: key 1BB943DB: public key "MariaDB Package Signing Key <package-signing-key@mariadb.org>" imported
==> sws: gpg: Total number processed: 1
==> sws: gpg:               imported: 1
==> sws: Error: /Stage[main]/Puphpet::Mariadb::Repo::Debian/Apt::Key[199369E5404BD5FC7D2FE43BCBCB082A1BB943DB]/Apt_key[199369E5404BD5FC7D2FE43BCBCB082A1BB943DB]/ensure: change from absent to present failed: Execution of '/usr/bin/apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 199369E5404BD5FC7D2FE43BCBCB082A1BB943DB' returned 2: Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.zsbfA8IECV --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/ondrej-apache2.gpg --keyring /etc/apt/trusted.gpg.d/pdoes-ppa.gpg --keyring /etc/apt/trusted.gpg.d/puppetlabs-pc1-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 199369E5404BD5FC7D2FE43BCBCB082A1BB943DB
==> sws: gpg: requesting key 1BB943DB from hkp server keyserver.ubuntu.com
==> sws: ?: [fd 4]: read error: Connection reset by peer
==> sws: gpgkeys: key 199369E5404BD5FC7D2FE43BCBCB082A1BB943DB partially retrieved (probably corrupt)
==> sws: gpg: no valid OpenPGP data found.
==> sws: gpg: key 1BB943DB: public key "MariaDB Package Signing Key <package-signing-key@mariadb.org>" imported
==> sws: gpg: Total number processed: 1
==> sws: gpg:               imported: 1
==> sws: Warning: /Stage[main]/Puphpet::Mariadb::Repo::Debian/Apt::Key[199369E5404BD5FC7D2FE43BCBCB082A1BB943DB]/Anchor[apt_key 199369E5404BD5FC7D2FE43BCBCB082A1BB943DB present]: Skipping because of failed dependencies
```

**Comment by jtreminio** [comment]
This should be fixed with newest version of boxes uploaded today.

If possible, downgrade to Virtualbox 5.0.26

**Comment by tetele** [comment]
Got the exact same error as @StudioMaX, using Vagrant 1.8.6 and VB 5.1.8. Today, with up-to-date boxes. Any ideas?

```
==> wp2p: Error: Facter: error while resolving custom fact "nodejs_latest_version": end of file reached
==> wp2p: Error: Facter: error while resolving custom fact "nodejs_stable_version": end of file reached
==> wp2p: Warning: The key 'shib2' is declared more than once at /tmp/vagrant-puppet/modules-c35193f0c0364450c873c712c66eecae/apache/manifests/params.pp:251:21
==> wp2p: Notice: Compiled catalog for wp2p.local in environment production in 5.92 seconds
==> wp2p: Info: Applying configuration version '1479227558'
==> wp2p: Info: Computing checksum on file /etc/timezone
==> wp2p: Info: FileBucket got a duplicate file {md5}4f24b133ba38d8fd565168742c9aedeb
==> wp2p: Info: /Stage[main]/Timezone/File[/etc/timezone]: Filebucketed /etc/timezone to puppet with sum 4f24b133ba38d8fd565168742c9aedeb
==> wp2p: Notice: /Stage[main]/Timezone/File[/etc/timezone]/content: content changed '{md5}4f24b133ba38d8fd565168742c9aedeb' to '{md5}ae1d80ba85332ae2d9fbbd491b17c043'
==> wp2p: Info: /Stage[main]/Timezone/File[/etc/timezone]: Scheduling refresh of Exec[update_timezone]
==> wp2p: Notice: /Stage[main]/Timezone/Exec[update_timezone]: Triggered 'refresh' from 1 events
==> wp2p: Notice: /Stage[main]/Puphpet::Server/Exec[dotfiles]/returns: executed successfully
==> wp2p: Notice: /Stage[main]/Puphpet::Mariadb::Server/Exec[Set pidfile parent directory permissions]/returns: executed successfully
==> wp2p: Notice: /Stage[main]/Puphpet::Mariadb::Repo::Debian/Apt::Key[199369E5404BD5FC7D2FE43BCBCB082A1BB943DB]/Anchor[apt_key 199369E5404BD5FC7D2FE43BCBCB082A1BB943DB present]: Dependency Apt_key[199369E5404BD5FC7D2FE43BCBCB082A1BB943DB] has failures: true
==> wp2p: Error: Execution of '/usr/bin/apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 199369E5404BD5FC7D2FE43BCBCB082A1BB943DB' returned 2: Executing: /tmp/tmp.x3aMTQpKep/gpg.1.sh --keyserver
==> wp2p: hkp://keyserver.ubuntu.com:80
==> wp2p: --recv-keys
==> wp2p: 199369E5404BD5FC7D2FE43BCBCB082A1BB943DB
==> wp2p: gpg: requesting key 1BB943DB from hkp server keyserver.ubuntu.com
==> wp2p: ?: [fd 4]: read error: Connection reset by peer
==> wp2p: gpgkeys: key 199369E5404BD5FC7D2FE43BCBCB082A1BB943DB partially retrieved (probably corrupt)
==> wp2p: gpg: no valid OpenPGP data found.
==> wp2p: gpg: key 1BB943DB: public key "MariaDB Package Signing Key <package-signing-key@mariadb.org>" imported
==> wp2p: gpg: Total number processed: 1
==> wp2p: gpg:               imported: 1
==> wp2p: Error: /Stage[main]/Puphpet::Mariadb::Repo::Debian/Apt::Key[199369E5404BD5FC7D2FE43BCBCB082A1BB943DB]/Apt_key[199369E5404BD5FC7D2FE43BCBCB082A1BB943DB]/ensure: change from absent to present failed: Execution of '/usr/bin/apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 199369E5404BD5FC7D2FE43BCBCB082A1BB943DB' returned 2: Executing: /tmp/tmp.x3aMTQpKep/gpg.1.sh --keyserver
==> wp2p: hkp://keyserver.ubuntu.com:80
==> wp2p: --recv-keys
==> wp2p: 199369E5404BD5FC7D2FE43BCBCB082A1BB943DB
==> wp2p: gpg: requesting key 1BB943DB from hkp server keyserver.ubuntu.com
==> wp2p: ?: [fd 4]: read error: Connection reset by peer
==> wp2p: gpgkeys: key 199369E5404BD5FC7D2FE43BCBCB082A1BB943DB partially retrieved (probably corrupt)
==> wp2p: gpg: no valid OpenPGP data found.
==> wp2p: gpg: key 1BB943DB: public key "MariaDB Package Signing Key <package-signing-key@mariadb.org>" imported
==> wp2p: gpg: Total number processed: 1
==> wp2p: gpg:               imported: 1
```

Config file is here http://pastebin.com/G5QvUXaV
